development:
  sessions:
    default:
      database: cryodex
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: cryodex
      hosts:
        - localhost:27017