development:
  sessions:
    default:
      database: cryodex
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
  options:
    identity_map_enabled: true
    scope_overwrite_exception: true
    skip_version_check: true